exports.__esModule = true;
exports["default"] = {
    "FFXIV Weather Bell": "最终幻想14天气时钟",
    "Zone": "地区",
    "Weather": "天气",
    "Previous Weather": "前置天气",
    "Time": "时间",
    "Any": "任意",
    "Local Time": "本地时间",
    "Eorzea Time": "艾欧泽亚时间",
    "Start Time": "开始时间",
    "End Time": "结束时间",
    "Weathers": "天气",
    "Show more": "显示更多",
    "Limsa Lominsa": "海都",
    "Middle La Noscea": "中拉诺西亚",
    "Lower La Noscea": "拉诺西亚低地",
    "Eastern La Noscea": "东拉诺西亚",
    "Western La Noscea": "西拉诺西亚",
    "Upper La Noscea": "拉诺西亚高地",
    "Outer La Noscea": "拉诺西亚外地",
    "The Mist": "海雾村",
    "Gridania": "森都",
    "Central Shroud": "黑衣森林中央林区",
    "East Shroud": "黑衣森林东部林区",
    "South Shroud": "黑衣森林南部林区",
    "North Shroud": "黑衣森林北部林区",
    "The Lavender Beds": "薰衣草苗圃",
    "Ul'dah": "沙都",
    "Western Thanalan": "西萨纳兰",
    "Central Thanalan": "中萨纳兰",
    "Eastern Thanalan": "东萨纳兰",
    "Southern Thanalan": "南萨纳兰",
    "Northern Thanalan": "北萨纳兰",
    "The Goblet": "高脚孤丘",
    "Ishgard": "伊修加德",
    "Coerthas Central Highlands": "库尔札斯中央高地",
    "Coerthas Western Highlands": "库尔札斯西部高地",
    "The Sea of Clouds": "阿巴拉提亚云海",
    "Azys Lla": "魔大陆阿济兹拉",
    "The Diadem": "空岛",
    "Idyllshire": "田园郡",
    "The Dravanian Forelands": "龙堡参天高地",
    "The Dravanian Hinterlands": "龙堡内陆低地",
    "The Churning Mists": "翻云雾海",
    "Mor Dhona": "摩杜纳",
    "Rhalgr's Reach": "神拳痕",
    "The Fringes": "基拉巴尼亚边区",
    "The Peaks": "基拉巴尼亚山区",
    "The Lochs": "基拉巴尼亚湖区",
    "Kugane": "黄金港",
    "Shirogane": "白银乡",
    "The Ruby Sea": "红玉海",
    "Yanxia": "延夏",
    "The Azim Steppe": "太阳神草原",
    "Eureka Anemos": "常风",
    "Eureka Pagos": "恒冰",
    "Eureka Pyros": "涌火",
    "Eureka Hydatos": "丰水",
    "The Crystarium": "水晶都",
    "Eulmore": "游末邦",
    "Lakeland": "雷克兰德",
    "Kholusia": "珂露西亚岛",
    "Amh Araeng": "安穆·艾兰",
    "Il Mheg": "伊尔美格",
    "The Rak'tika Greatwood": "拉凯提卡大森林",
    "The Tempest": "黑风海",
    "Clouds": "阴云",
    "Clear Skies": "碧空",
    "Fair Skies": "晴朗",
    "Fog": "薄雾",
    "Rain": "小雨",
    "Wind": "微风",
    "Showers": "暴雨",
    "Gales": "强风",
    "Thunder": "打雷",
    "Thunderstorms": "雷雨",
    "Dust Storms": "扬沙",
    "Heat Waves": "热浪",
    "Gloom": "妖雾",
    "Snow": "小雪",
    "Blizzards": "暴雪",
    "Umbral Wind": "灵风",
    "Umbral Static": "灵电"
};
