var commands = [
    {"func":0,"param":true,"command":"攻略"},
    {"func":1,"param":true,"command":"CD"},
    {"func":1,"param":true,"command":"cd"},
    {"func":2,"param":false,"command":"祈福"},
    {"func":2,"param":false,"command":"欺负"},
    {"func":3,"param":true,"command":"常见问题"},
    {"func":4,"param":true,"command":"传说"},
    {"func":5,"param":false,"command":"四大天王"},
    //{"func":6,"param":false,"command":"help"},
    //{"func":6,"param":false,"command":"帮助"},
    //{"func":7,"param":false,"command":"占卜"},
    //{"func":7,"param":false,"command":"luck"},
    //{"func":8,"param":true,"command":"查价"}, //大区
    {"func":9,"param":true,"command":"帮我选"},
    {"func":10,"param":false,"command":"海钓航线"},
    {"func":10,"param":false,"command":"海钓航班"},
    {"func":11,"param":true,"command":"鱼王"},
    {"func":12,"param":true,"command":"开启"},
    {"func":13,"param":true,"command":"关闭"},
    {"func":14,"param":true,"command":"报时添加"},
    {"func":15,"param":true,"command":"报时删除"},
    {"func":16,"param":false,"command":"报时列表"},
    //{"func":17,"param":false,"command":"修改欢迎消息"},
    //{"func":18,"param":false,"command":"暖暖"},
    //{"func":18,"param":false,"command":"nuannuan"},
    //{"func":19,"param":false,"command":"二次元"},
    //{"func":19,"param":false,"command":"带我去二次元"},
    //{"func":19,"param":false,"command":"色图"},
]

module.exports = commands;
